name: Build & Deploy .NET App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  PUBLISH_PATH: '.'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.nuget/packages 
    # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.PUBLISH_PATH }}/publish'
    outputs:
      publish_package: '${{ env.PUBLISH_PATH }}/publish'
  
  deploy:
    needs: build #making build as a prerequisite job to complete
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ needs.build.outputs.publish_package }}'
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: dotnet-learners-house-demo
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
        package: '${{ needs.build.outputs.publish_package }}'
  
    
